# =============================================================================
# Project Title: Wild Boar Distribution Model for France
# Path: featureconfig.yaml
# Purpose: Configuration for variable grouping and selection behaviour.
# Process Step: Controls which predictors are kept or discarded during training.
# Created by Adrian Meyer, Institute Geomatics, FHNW (adrian.meyer@fhnw.ch)
# Created: July 2025
# Version: v.0.1.0
# =============================================================================
# Cases: keep, drop
# keep -> retain variable
# drop -> always discard

variables:
  2017_04_bsi: keep
  2017_04_evi: keep
  2017_04_evi2: keep
  2017_04_nbr: drop
  2017_04_ndbi: drop
  2017_04_ndmi: drop
  2017_04_ndsi: keep
  2017_04_ndvi: keep
  2017_04_ndwi: keep
  2017_04_vssi: drop
  2017_07_bsi: keep
  2017_07_evi: keep
  2017_07_evi2: keep
  2017_07_nbr: drop
  2017_07_ndbi: drop
  2017_07_ndmi: drop
  2017_07_ndsi: keep
  2017_07_ndvi: keep
  2017_07_ndwi: keep
  2017_07_vssi: drop
  2017_10_bsi: keep
  2017_10_evi: keep
  2017_10_evi2: keep
  2017_10_nbr: keep
  2017_10_ndbi: keep
  2017_10_ndmi: keep
  2017_10_ndsi: keep
  2017_10_ndvi: keep
  2017_10_ndwi: keep
  2017_10_vssi: drop
  2017_class0_BGROUND: keep
  2017_class10_BEECHGRV: keep
  2017_class11_URBAN: keep
  2017_class12_WATER: keep
  2017_class13_OTHER: keep
  2017_class1_WHEAT: keep
  2017_class2_CORNMAIZ: keep
  2017_class3_BARLEY: keep
  2017_class4_RAPESEED: keep
  2017_class5_AGRILAND: keep
  2017_class6_GRASSLND: keep
  2017_class7_OAKGROVE: keep
  2017_class8_CONIFERS: keep
  2017_class9_MIXFORST: keep
  2018_04_bsi: drop
  2018_04_evi: drop
  2018_04_evi2: drop
  2018_04_nbr: drop
  2018_04_ndbi: drop
  2018_04_ndmi: drop
  2018_04_ndsi: drop
  2018_04_ndvi: drop
  2018_04_ndwi: drop
  2018_04_vssi: drop
  2018_07_bsi: keep
  2018_07_evi: keep
  2018_07_evi2: keep
  2018_07_nbr: keep
  2018_07_ndbi: keep
  2018_07_ndmi: keep
  2018_07_ndsi: keep
  2018_07_ndvi: keep
  2018_07_ndwi: keep
  2018_07_vssi: drop
  2018_10_bsi: keep
  2018_10_evi: keep
  2018_10_evi2: keep
  2018_10_nbr: keep
  2018_10_ndbi: keep
  2018_10_ndmi: keep
  2018_10_ndsi: keep
  2018_10_ndvi: keep
  2018_10_ndwi: keep
  2018_10_vssi: drop
  2018_class0_BGROUND: keep
  2018_class10_BEECHGRV: keep
  2018_class11_URBAN: keep
  2018_class12_WATER: keep
  2018_class13_OTHER: keep
  2018_class1_WHEAT: keep
  2018_class2_CORNMAIZ: keep
  2018_class3_BARLEY: keep
  2018_class4_RAPESEED: keep
  2018_class5_AGRILAND: keep
  2018_class6_GRASSLND: keep
  2018_class7_OAKGROVE: keep
  2018_class8_CONIFERS: keep
  2018_class9_MIXFORST: keep
  2019_04_bsi: drop
  2019_04_evi: drop
  2019_04_evi2: drop
  2019_04_nbr: drop
  2019_04_ndbi: drop
  2019_04_ndmi: drop
  2019_04_ndsi: drop
  2019_04_ndvi: drop
  2019_04_ndwi: drop
  2019_04_vssi: drop
  2019_07_bsi: keep
  2019_07_evi: keep
  2019_07_evi2: keep
  2019_07_nbr: keep
  2019_07_ndbi: keep
  2019_07_ndmi: keep
  2019_07_ndsi: keep
  2019_07_ndvi: keep
  2019_07_ndwi: keep
  2019_07_vssi: drop
  2019_10_bsi: keep
  2019_10_evi: keep
  2019_10_evi2: keep
  2019_10_nbr: keep
  2019_10_ndbi: keep
  2019_10_ndmi: keep
  2019_10_ndsi: keep
  2019_10_ndvi: keep
  2019_10_ndwi: keep
  2019_10_vssi: drop
  2019_class0_BGROUND: keep
  2019_class10_BEECHGRV: keep
  2019_class11_URBAN: keep
  2019_class12_WATER: keep
  2019_class13_OTHER: keep
  2019_class1_WHEAT: keep
  2019_class2_CORNMAIZ: keep
  2019_class3_BARLEY: keep
  2019_class4_RAPESEED: keep
  2019_class5_AGRILAND: keep
  2019_class6_GRASSLND: keep
  2019_class7_OAKGROVE: keep
  2019_class8_CONIFERS: keep
  2019_class9_MIXFORST: keep
  2020_04_bsi: drop
  2020_04_evi: drop
  2020_04_evi2: drop
  2020_04_nbr: drop
  2020_04_ndbi: drop
  2020_04_ndmi: drop
  2020_04_ndsi: drop
  2020_04_ndvi: drop
  2020_04_ndwi: drop
  2020_04_vssi: drop
  2020_07_bsi: keep
  2020_07_evi: keep
  2020_07_evi2: keep
  2020_07_nbr: keep
  2020_07_ndbi: keep
  2020_07_ndmi: keep
  2020_07_ndsi: keep
  2020_07_ndvi: keep
  2020_07_ndwi: keep
  2020_07_vssi: drop
  2020_10_bsi: keep
  2020_10_evi: keep
  2020_10_evi2: keep
  2020_10_nbr: keep
  2020_10_ndbi: keep
  2020_10_ndmi: keep
  2020_10_ndsi: keep
  2020_10_ndvi: keep
  2020_10_ndwi: keep
  2020_10_vssi: drop
  2020_class0_BGROUND: keep
  2020_class10_BEECHGRV: keep
  2020_class11_URBAN: keep
  2020_class12_WATER: keep
  2020_class13_OTHER: keep
  2020_class1_WHEAT: keep
  2020_class2_CORNMAIZ: keep
  2020_class3_BARLEY: keep
  2020_class4_RAPESEED: keep
  2020_class5_AGRILAND: keep
  2020_class6_GRASSLND: keep
  2020_class7_OAKGROVE: keep
  2020_class8_CONIFERS: keep
  2020_class9_MIXFORST: keep
  2021_04_bsi: keep
  2021_04_evi: keep
  2021_04_evi2: keep
  2021_04_nbr: keep
  2021_04_ndbi: keep
  2021_04_ndmi: keep
  2021_04_ndsi: keep
  2021_04_ndvi: keep
  2021_04_ndwi: keep
  2021_04_vssi: drop
  2021_07_bsi: keep
  2021_07_evi: keep
  2021_07_evi2: keep
  2021_07_nbr: keep
  2021_07_ndbi: keep
  2021_07_ndmi: keep
  2021_07_ndsi: keep
  2021_07_ndvi: keep
  2021_07_ndwi: keep
  2021_07_vssi: drop
  2021_10_bsi: keep
  2021_10_evi: keep
  2021_10_evi2: keep
  2021_10_nbr: keep
  2021_10_ndbi: keep
  2021_10_ndmi: keep
  2021_10_ndsi: keep
  2021_10_ndvi: keep
  2021_10_ndwi: keep
  2021_10_vssi: drop
  2021_class0_BGROUND: keep
  2021_class10_BEECHGRV: keep
  2021_class11_URBAN: keep
  2021_class12_WATER: keep
  2021_class13_OTHER: keep
  2021_class1_WHEAT: keep
  2021_class2_CORNMAIZ: keep
  2021_class3_BARLEY: keep
  2021_class4_RAPESEED: keep
  2021_class5_AGRILAND: keep
  2021_class6_GRASSLND: keep
  2021_class7_OAKGROVE: keep
  2021_class8_CONIFERS: keep
  2021_class9_MIXFORST: keep
  2022_04_bsi: keep
  2022_04_evi: keep
  2022_04_evi2: keep
  2022_04_nbr: keep
  2022_04_ndbi: keep
  2022_04_ndmi: keep
  2022_04_ndsi: keep
  2022_04_ndvi: keep
  2022_04_ndwi: keep
  2022_04_vssi: drop
  2022_07_bsi: keep
  2022_07_evi: keep
  2022_07_evi2: keep
  2022_07_nbr: keep
  2022_07_ndbi: keep
  2022_07_ndmi: keep
  2022_07_ndsi: keep
  2022_07_ndvi: keep
  2022_07_ndwi: keep
  2022_07_vssi: drop
  2022_10_bsi: drop
  2022_10_evi: drop
  2022_10_evi2: drop
  2022_10_nbr: drop
  2022_10_ndbi: drop
  2022_10_ndmi: drop
  2022_10_ndsi: drop
  2022_10_ndvi: drop
  2022_10_ndwi: drop
  2022_10_vssi: drop
  2022_class0_BGROUND: keep
  2022_class10_BEECHGRV: keep
  2022_class11_URBAN: keep
  2022_class12_WATER: keep
  2022_class13_OTHER: keep
  2022_class1_WHEAT: keep
  2022_class2_CORNMAIZ: keep
  2022_class3_BARLEY: keep
  2022_class4_RAPESEED: keep
  2022_class5_AGRILAND: keep
  2022_class6_GRASSLND: keep
  2022_class7_OAKGROVE: keep
  2022_class8_CONIFERS: keep
  2022_class9_MIXFORST: keep
  2023_04_bsi: keep
  2023_04_evi: keep
  2023_04_evi2: keep
  2023_04_nbr: keep
  2023_04_ndbi: keep
  2023_04_ndmi: keep
  2023_04_ndsi: keep
  2023_04_ndvi: keep
  2023_04_ndwi: keep
  2023_04_vssi: drop
  2023_07_bsi: drop
  2023_07_evi: drop
  2023_07_evi2: drop
  2023_07_nbr: drop
  2023_07_ndbi: drop
  2023_07_ndmi: drop
  2023_07_ndsi: drop
  2023_07_ndvi: drop
  2023_07_ndwi: drop
  2023_07_vssi: drop
  2023_10_bsi: keep
  2023_10_evi: keep
  2023_10_evi2: keep
  2023_10_nbr: keep
  2023_10_ndbi: keep
  2023_10_ndmi: keep
  2023_10_ndsi: keep
  2023_10_ndvi: keep
  2023_10_ndwi: keep
  2023_10_vssi: drop
  2023_class0_BGROUND: keep
  2023_class10_BEECHGRV: keep
  2023_class11_URBAN: keep
  2023_class12_WATER: keep
  2023_class13_OTHER: keep
  2023_class1_WHEAT: keep
  2023_class2_CORNMAIZ: keep
  2023_class3_BARLEY: keep
  2023_class4_RAPESEED: keep
  2023_class5_AGRILAND: keep
  2023_class6_GRASSLND: keep
  2023_class7_OAKGROVE: keep
  2023_class8_CONIFERS: keep
  2023_class9_MIXFORST: keep
  2024_04_bsi: drop
  2024_04_evi: drop
  2024_04_evi2: drop
  2024_04_nbr: drop
  2024_04_ndbi: drop
  2024_04_ndmi: drop
  2024_04_ndsi: drop
  2024_04_ndvi: drop
  2024_04_ndwi: drop
  2024_04_vssi: drop
  2024_07_bsi: keep
  2024_07_evi: keep
  2024_07_evi2: keep
  2024_07_nbr: keep
  2024_07_ndbi: keep
  2024_07_ndmi: keep
  2024_07_ndsi: keep
  2024_07_ndvi: keep
  2024_07_ndwi: keep
  2024_07_vssi: drop
  2024_10_bsi: keep
  2024_10_evi: keep
  2024_10_evi2: keep
  2024_10_nbr: keep
  2024_10_ndbi: keep
  2024_10_ndmi: keep
  2024_10_ndsi: keep
  2024_10_ndvi: keep
  2024_10_ndwi: keep
  2024_10_vssi: drop
  2017_class0_BGROUND_distance: drop
  2017_class10_BEECHGRV_distance: keep
  2017_class11_URBAN_distance: keep
  2017_class12_WATER_distance: keep
  2017_class13_OTHER_distance: drop
  2017_class1_WHEAT_distance: keep
  2017_class2_CORNMAIZ_distance: keep
  2017_class3_BARLEY_distance: keep
  2017_class4_RAPESEED_distance: keep
  2017_class5_AGRILAND_distance: keep
  2017_class6_GRASSLND_distance: keep
  2017_class7_OAKGROVE_distance: keep
  2017_class8_CONIFERS_distance: keep
  2017_class9_MIXFORST_distance: keep
  2018_class0_BGROUND_distance: drop
  2018_class10_BEECHGRV_distance: keep
  2018_class11_URBAN_distance: keep
  2018_class12_WATER_distance: keep
  2018_class13_OTHER_distance: drop
  2018_class1_WHEAT_distance: keep
  2018_class2_CORNMAIZ_distance: keep
  2018_class3_BARLEY_distance: keep
  2018_class4_RAPESEED_distance: keep
  2018_class5_AGRILAND_distance: keep
  2018_class6_GRASSLND_distance: keep
  2018_class7_OAKGROVE_distance: keep
  2018_class8_CONIFERS_distance: keep
  2018_class9_MIXFORST_distance: keep
  2019_class0_BGROUND_distance: drop
  2019_class10_BEECHGRV_distance: keep
  2019_class11_URBAN_distance: keep
  2019_class12_WATER_distance: keep
  2019_class13_OTHER_distance: drop
  2019_class1_WHEAT_distance: keep
  2019_class2_CORNMAIZ_distance: keep
  2019_class3_BARLEY_distance: keep
  2019_class4_RAPESEED_distance: keep
  2019_class5_AGRILAND_distance: keep
  2019_class6_GRASSLND_distance: keep
  2019_class7_OAKGROVE_distance: keep
  2019_class8_CONIFERS_distance: keep
  2019_class9_MIXFORST_distance: keep
  2020_class0_BGROUND_distance: drop
  2020_class10_BEECHGRV_distance: keep
  2020_class11_URBAN_distance: keep
  2020_class12_WATER_distance: keep
  2020_class13_OTHER_distance: drop
  2020_class1_WHEAT_distance: keep
  2020_class2_CORNMAIZ_distance: keep
  2020_class3_BARLEY_distance: keep
  2020_class4_RAPESEED_distance: keep
  2020_class5_AGRILAND_distance: keep
  2020_class6_GRASSLND_distance: keep
  2020_class7_OAKGROVE_distance: keep
  2020_class8_CONIFERS_distance: keep
  2020_class9_MIXFORST_distance: keep
  2021_class0_BGROUND_distance: drop
  2021_class10_BEECHGRV_distance: keep
  2021_class11_URBAN_distance: keep
  2021_class12_WATER_distance: keep
  2021_class13_OTHER_distance: drop
  2021_class1_WHEAT_distance: keep
  2021_class2_CORNMAIZ_distance: keep
  2021_class3_BARLEY_distance: keep
  2021_class4_RAPESEED_distance: keep
  2021_class5_AGRILAND_distance: keep
  2021_class6_GRASSLND_distance: keep
  2021_class7_OAKGROVE_distance: keep
  2021_class8_CONIFERS_distance: keep
  2021_class9_MIXFORST_distance: keep
  2022_class0_BGROUND_distance: drop
  2022_class10_BEECHGRV_distance: keep
  2022_class11_URBAN_distance: keep
  2022_class12_WATER_distance: keep
  2022_class13_OTHER_distance: drop
  2022_class1_WHEAT_distance: keep
  2022_class2_CORNMAIZ_distance: keep
  2022_class3_BARLEY_distance: keep
  2022_class4_RAPESEED_distance: keep
  2022_class5_AGRILAND_distance: keep
  2022_class6_GRASSLND_distance: keep
  2022_class7_OAKGROVE_distance: keep
  2022_class8_CONIFERS_distance: keep
  2022_class9_MIXFORST_distance: keep
  2023_class0_BGROUND_distance: drop
  2023_class10_BEECHGRV_distance: keep
  2023_class11_URBAN_distance: keep
  2023_class12_WATER_distance: keep
  2023_class13_OTHER_distance: drop
  2023_class1_WHEAT_distance: keep
  2023_class2_CORNMAIZ_distance: keep
  2023_class3_BARLEY_distance: keep
  2023_class4_RAPESEED_distance: keep
  2023_class5_AGRILAND_distance: keep
  2023_class6_GRASSLND_distance: keep
  2023_class7_OAKGROVE_distance: keep
  2023_class8_CONIFERS_distance: keep
  2023_class9_MIXFORST_distance: keep
  DEM_Altitude: keep
  DEM_Aspect: keep
  DEM_Elevation_Range: keep
  DEM_Slope: keep
  DEM_Terrain_Ruggedness: keep
  LC01_Dense_Urbanization: keep
  LC03_Industrial_Zones: keep
  LC14_Fruit_Orchards: keep
  LC15_Vineyards: keep
  LC19_Natural_Heath: keep
  LC20_Rocky_Surfaces: drop
  LC21_Beaches_Dunes: drop
  LC22_Snowy_Glaciers: drop
  LC01_Dense_Urbanization_distance: keep
  LC03_Industrial_Zones_distance: keep
  LC14_Fruit_Orchards_distance: keep
  LC15_Vineyards_distance: keep
  LC19_Natural_Heath_distance: keep
  LC20_Rocky_Surfaces_distance: drop
  LC21_Beaches_Dunes_distance: drop
  LC22_Snowy_Glaciers_distance: drop
  Zones_humides_INPN: keep
  bio01-ann_mean_temp: keep
  bio02_mean_diurnal_range: keep
  bio03_isothermality: keep
  bio04_temp_seasonality: keep
  bio05_max_temp_warmest_m: keep
  bio06_min_temp_coldest_m: keep
  bio07_temp_ann_range: keep
  bio08_mean_temp_wettest_q: drop
  bio09_mean_temp_driest_q: drop
  bio10_mean_temp_warmest_q: keep
  bio11_mean_temp_coldest_q: keep
  bio12_ann_precip: keep
  bio13_precip_wettest: keep
  bio14_precip_driest: keep
  bio15_precip_seasonality: keep
  bio16_precip_wettest_q: keep
  bio17_precip_driest_q: keep
  bio18_precip_warmest_q: drop
  bio19_precip_coldest_q: drop
  fragmentation_density: keep
  hunting_bag_2017: keep
  hunting_bag_2018: keep
  hunting_bag_2019: keep
  hunting_bag_2020: keep
  hunting_bag_2021: keep
  hunting_bag_2022: keep
  hunting_bag_2023: keep
  small_woody_features: keep
  wildareas_humanfootprint: drop
